Cm 14 base page
frontend-park-mail-ru/2021_1_Code_Magicians pull request #10
Opened 2021-03-16 23:52 UTC by GrateJastes

2021-03-17 10:00 UTC, Sarafa2n requested changes

2021-03-17 10:00 UTC, Sarafa2n commented on src/components/page/page.hbs
> +    <div class="page__content"></div>
У тебя `sidebar` и `content` можно обернуть в `<div>`

2021-03-17 10:00 UTC, Sarafa2n commented on src/components/sidebar/sidebar.hbs
> +            </div>
ЭЭЭ, это делается вообще по другому, через псевдоэлемент у иконки домой и другой

2021-03-17 10:00 UTC, Sarafa2n commented on src/components/sidebar/sidebar.hbs
> +                <img src="assets/img/svg/page__sidebar/Home.svg" alt="Home" class="view-selector__option__icon">
класс не по БЭМу

2021-03-17 10:00 UTC, Sarafa2n commented on src/components/sidebar/sidebar.hbs
> +                <img src="assets/img/svg/page__sidebar/Selector.svg" alt="logo" class="view-selector__option__mark__image"">
В БЭМ можно **только**  один раз __

2021-03-17 10:00 UTC, Sarafa2n commented on src/components/sidebar/sidebar.scss
> +      zoom: 105%;
лучше использовать `scale()`

2021-03-17 10:00 UTC, Sarafa2n commented on src/components/sidebar/sidebar.scss
> +      zoom: 120%;
тут тоже самое

2021-03-17 10:00 UTC, Sarafa2n commented on src/components/navbar/navbar.scss
> +    margin-right: -30px;
Не используй отрицательные значения, кажется неправильно сделано

2021-03-17 10:00 UTC, Sarafa2n commented on src/index.js
> +  },
((

2021-03-17 10:56 UTC, GrateJastes commented on src/components/navbar/navbar.scss
> +    margin-right: -30px;
А как это иначе делается? Вариант с отрицательными марджинами очень многие рекомендуют для того, чтобы один элемент на другой наложить (как в моем случае)

2021-03-17 10:57 UTC, GrateJastes commented on src/index.js
> +  },
Ну, про это я уже говорил. Это я сделаю по-другому, но пока не знаю, как. Почитай сообщения, плиз(

2021-03-17 10:59 UTC, GrateJastes commented on src/components/page/page.hbs
> +    <div class="page__content"></div>
Зачем и по какой логике? 0_o
Они же по смыслу совсем не так расположены. `sidebar` и `navbar`  образуют уголок в левой и верхней частях окна. И они `fixed`, остаются при прокрутке страницы. А контент находится во всем оставшемся месте кроме этого уголка. Это плохая структура?

2021-03-17 11:03 UTC, GrateJastes commented on src/components/page/page.hbs
> +    <div class="page__content"></div>
Тогда уж `navbar` и `content` можно было бы объединять - у них хотя бы одинаковая ширина (хотя и принципиально разное поведение и смысл). Но у `sidebar` и `content` нет точно ничего общего

2021-03-20 08:06 UTC, Sarafa2n requested changes

2021-03-20 08:06 UTC, Sarafa2n commented on src/assets/css/base.css
> +    /*--black: rgba(51, 51, 51, 1);*/
Что за комменты?
Если это темная тема, то вынеси это в отдельный root

2021-03-20 08:06 UTC, Sarafa2n commented on src/components/navbar/navbar.hbs
> +            <button class="navbar__user-change-button">
кажется это можно назвать просто `navbar__toggle`

2021-03-20 08:06 UTC, Sarafa2n commented on src/components/navbar/navbar.scss
> +  }
можно `hover` занести в `&__search-wiper` вот так  `&:hover`

2021-03-20 08:06 UTC, Sarafa2n commented on src/components/page/page.hbs
> +    </div>
лучше `page__wrap` в котором `navbar` и `content` потому что будет проще менять  экраны

2021-03-20 08:06 UTC, Sarafa2n commented on src/components/sidebar/sidebar.hbs
> +        <div class="view-selector__option">
кажется это `item`, а не `option`

2021-03-20 08:06 UTC, Sarafa2n commented on src/components/sidebar/sidebar.scss
> +}
кажется можно внести в `.slider-button`

2021-03-20 08:06 UTC, Sarafa2n commented on src/components/sidebar/sidebar.scss
> +.slider-button {
кажется это не `slider-button`, а `popup-toggle`

2021-03-20 10:25 UTC, Sarafa2n approved these changes

2021-03-20 10:25 UTC, merged