Cm 5 profile
frontend-park-mail-ru/2021_1_Code_Magicians pull request #14
Opened 2021-03-27 22:41 UTC by GrateJastes

Это пока что только для ревью. Посмотри, пожалуйста, как я переделал архитектуру с Page. Мне кажется, это довольно элегантное и логичное решение, хотя хз) В любом случае, обрати внимание, пожалуйста)
В приложении будет несколько view, наследующихся от ProfileView (ProfileBoardsView, ProfilePinsView, ProfileFollowersView и т.д.). Они все имеют шапку профиля и отличаются только содержимым. Я не уверен в этом решении, ибо перерисовывать эти вьюхи - большой оверхед (хотя, когда будет virtual DOM, возможно, будет норм). Кажется, что можно было бы сделать эти переходы, не меняя вьюху, но тогда придется криво и вручную пушить в историю и изменять path при переходах. С другой стороны по сути это разные view, и на них должны быть разные URLы и переход по истории, они используют разные данные и т.д. В общем, это тоже, пожалуйста, прокомментируй.

2021-03-28 08:50 UTC, Sarafa2n requested changes

2021-03-28 08:50 UTC, Sarafa2n commented on src/components/profileHeader/profileHeader.js
> +    return tmpl(this.props);
зачем проброс в шаблон, если ты ничего не делаешь с данными.
И лучше использовать spread оператор

2021-03-28 08:50 UTC, Sarafa2n commented on src/views/view.js
> +    }
зачем так-то, а не проще было добавить в Page.hbs переменную, и в нее класть шаблон ?

2021-03-29 19:44 UTC, Sarafa2n requested changes

2021-03-29 19:44 UTC, Sarafa2n commented on server/index.js
> +  console.log(req.path);
нужно убрать консоль лог

2021-03-29 19:44 UTC, Sarafa2n commented on src/components/navbar/navbar.hbs
>              <a href="/signin" class="navbar__auth-link navbar__auth-link_signin">Sign in</a>
кажется это не модификатор

2021-03-29 19:44 UTC, Sarafa2n commented on src/components/navbar/navbar.hbs
> +        <img src="/assets/img/svg/page__navbar/Search.svg" alt="Search" class="navbar__search-icon">
давай переделаем подключение иконок

2021-03-29 19:44 UTC, Sarafa2n commented on src/components/notificationSettings/notificationSettings.hbs
> +</p>
не понял

2021-03-29 19:44 UTC, Sarafa2n commented on src/components/page/page.scss
> +  height: 100%;
наоборот, сначала height потом padding

2021-03-29 19:44 UTC, Sarafa2n commented on src/components/profileHeader/profileHeader.js
> +          // link.classList.remove('profile-links__link_active');
комментарий надо убрать

2021-03-29 19:44 UTC, Sarafa2n commented on src/components/profileHeader/profileHeader.js
> +        .forEach(link => {
скобки

2021-03-29 19:44 UTC, Sarafa2n commented on src/components/profileHeader/profileHeader.js
> +          if (link.getAttribute('data-target') === this._state.section) {
переделай на a.href

2021-03-29 19:44 UTC, Sarafa2n commented on src/components/securitySettings/securitySettings.hbs
> +            <input type="password" class="settings__field-input" placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;">
что это такое

2021-03-29 19:44 UTC, Sarafa2n commented on src/consts/consts.js
> +    frontendURL: `http://${window.location.hostname}:3000`,
кажется она не нужна

2021-03-29 19:44 UTC, Sarafa2n commented on src/views/notFoundView/notFoundView.hbs
> +<div class="not-found">
переименовать класс надо

2021-04-02 18:29 UTC, Sarafa2n requested changes

2021-04-02 18:29 UTC, Sarafa2n commented on server/index.js
> +const port = 8081;
давай порт передавать из терминала, и если он не был передан, то пусть будет 3000

2021-04-02 18:29 UTC, Sarafa2n commented on src/components/profileChanges/profileChanges.js
> +      alert('username invalid');
зачем alert? давай уберем

2021-04-02 18:29 UTC, Sarafa2n commented on src/components/profileHeader/profileHeader.scss
> +    :hover {
эм кажется чет пропало

2021-04-03 15:40 UTC, Sarafa2n requested changes

2021-04-03 15:40 UTC, Sarafa2n commented on server/index.js
> +const port = process.argv[2] || 3000;
эм, а почему не написать process.env.port ?

2021-04-03 15:40 UTC, Sarafa2n commented on src/actions/actions.js
> +    statusProcessed: 'error-processed',
почему где-то есть  Views, а где-то нет? кажется если это action нужно без views

2021-04-03 15:40 UTC, Sarafa2n commented on src/index.html
> +    <script src="https://kit.fontawesome.com/5b45e01240.js" crossorigin="anonymous"></script>
а почему не подключить обычный пакет, уже готовый? 
Зачем собирать свой?

2021-04-03 15:40 UTC, Sarafa2n commented on src/modules/eventMixin.js
> +    if (!this._listeners[event]) return;
давай писать {} даже если одна строка

2021-04-03 15:40 UTC, Sarafa2n commented on src/modules/validator.js
> +};
эм?

2021-04-03 16:11 UTC, GrateJastes commented on src/actions/actions.js
> +    statusProcessed: 'error-processed',
это все тот же косяк с переименованием до сих пор тянется...(

2021-04-03 16:15 UTC, GrateJastes commented on src/actions/actions.js
> +    statusProcessed: 'error-processed',
Теперь, вроде, все довыпилил

2021-04-03 16:20 UTC, GrateJastes commented on src/modules/validator.js
> +};
мусор

2021-04-03 17:01 UTC, Sarafa2n approved these changes

2021-04-03 17:01 UTC, merged