CM-20_ProfilesStore
frontend-park-mail-ru/2021_1_Code_Magicians pull request #16
Opened 2021-04-05 10:44 UTC by GrateJastes

2021-04-05 17:47 UTC, Sarafa2n requested changes

2021-04-05 17:47 UTC, Sarafa2n commented on src/stores/profilesStore/profilesStore.js
> +          console.log(`Profile ${follow ? '' : 'un'}following error. Status: `, response.status);
консоль ((

2021-04-05 17:47 UTC, Sarafa2n commented on src/stores/profilesStore/profilesStore.js
> +          }
давай либо то, либо это

2021-04-05 17:55 UTC, GrateJastes commented on src/stores/profilesStore/profilesStore.js
> +          }
не очень понял, что имеется в виду?

2021-04-05 17:55 UTC, GrateJastes commented on src/stores/profilesStore/profilesStore.js
> +          console.log(`Profile ${follow ? '' : 'un'}following error. Status: `, response.status);
А это плохо? Сообщения то об ошибках, которых вообще не должно происходить на проде, если пользователь в исходники не лезет

2021-04-05 18:17 UTC, Sarafa2n commented on src/stores/profilesStore/profilesStore.js
> +          }
`if` и тернарник, лучше уж 2 `if`

2021-04-07 16:33 UTC, Sarafa2n approved these changes

2021-04-07 16:47 UTC, merged