Cm 19 pins store
frontend-park-mail-ru/2021_1_Code_Magicians pull request #17
Opened 2021-04-05 10:45 UTC by GrateJastes

2021-04-05 17:44 UTC, Sarafa2n requested changes

2021-04-05 17:44 UTC, Sarafa2n commented on src/modules/http.js
> +        };
кажется можно обойтись без дублирования кода

2021-04-05 17:44 UTC, Sarafa2n commented on src/stores/pinsStore/pinsStore.js
> +const pinsGenerator = function* () {
опять генератор ??

2021-04-05 17:44 UTC, Sarafa2n commented on src/stores/pinsStore/pinsStore.js
> +          console.log('Pin creating error. Status: ', response.status);
консоль ((

2021-04-05 17:44 UTC, Sarafa2n commented on src/stores/pinsStore/pinsStore.js
> +          this._pin = this._pin ? this._pin.ID === pinID ? null : this._pin : null;
чет сложно, давай переделаем

2021-04-05 17:53 UTC, GrateJastes commented on src/stores/pinsStore/pinsStore.js
> +          console.log('Pin creating error. Status: ', response.status);
А это плохо? Сообщения то об ошибках, которых вообще не должно происходить на проде, если пользователь в исходники не лезет

2021-04-05 17:54 UTC, GrateJastes commented on src/stores/pinsStore/pinsStore.js
> +          this._pin = this._pin ? this._pin.ID === pinID ? null : this._pin : null;
ок, какой-то полет фантазии произошел)

2021-04-07 16:26 UTC, Sarafa2n approved these changes

2021-04-07 16:58 UTC, merged