CM-21_BoardsStore
frontend-park-mail-ru/2021_1_Code_Magicians pull request #18
Opened 2021-04-05 11:42 UTC by GrateJastes

2021-04-05 17:33 UTC, Sarafa2n requested changes

2021-04-05 17:33 UTC, Sarafa2n commented on src/modules/api.js
> +   * @return {Promise<{headers: Headers, responseBody: {}, status: number}>}
давай пока это оставим до TS

2021-04-05 17:33 UTC, Sarafa2n commented on src/stores/boardsStore/boardsStore.js
> +const boardsGenerator = function* () {
а зачем здесь генератор?

2021-04-05 17:33 UTC, Sarafa2n commented on src/stores/boardsStore/boardsStore.js
> +          console.log('Board deleting error. Status: ', response.status);
в проде не должно быть `console.log`

2021-04-05 17:56 UTC, GrateJastes commented on src/modules/api.js
> +   * @return {Promise<{headers: Headers, responseBody: {}, status: number}>}
А это автогенерация подсказывает в IDEшке, так удобнее автодополнение работает, подсветка синтаксиса и т.д. Это очень критично?

2021-04-05 17:59 UTC, GrateJastes commented on src/stores/boardsStore/boardsStore.js
> +          console.log('Board deleting error. Status: ', response.status);
А чем тогда его заменять? Это именно логирование и нужно оно, по сути, только при отладке. Ибо при стабильной работе приложения этих ошибок возникать вообще не должно, и это контролируется фронтом (кроме ошибки сервера, которой в общем то тоже не место на бою). Как быть с такими данными? Вообще игнорировать их? Или можно все-таки в целях отладки для них что-то иметь?

2021-04-05 18:02 UTC, GrateJastes commented on src/stores/boardsStore/boardsStore.js
> +const boardsGenerator = function* () {
Для экономии места) В питоне так принято заполнять однообразные массивы. Мне показалось, что это будет удобно Там же написано, это все равно мок, пока не существует апи для таких запросов (это даже не к текущему РК задача). Короч, чтобы не писать огромную стену текста feedBoards = [ new Board({...}, new Board{...}, new.....];

2021-04-05 18:03 UTC, Sarafa2n commented on src/modules/api.js
> +   * @return {Promise<{headers: Headers, responseBody: {}, status: number}>}
ну нет, просто как предложение

2021-04-05 18:06 UTC, Sarafa2n commented on src/stores/boardsStore/boardsStore.js
> +          console.log('Board deleting error. Status: ', response.status);
ну так отлаживать надо локально, а в проде код, который работает

2021-04-07 16:35 UTC, Sarafa2n approved these changes

2021-04-07 16:36 UTC, merged