Cm 1 cm 2 login signup pages
frontend-park-mail-ru/2021_1_Code_Magicians pull request #19
Opened 2021-04-05 14:29 UTC by doomwastaken

Добавил базовые версии страниц на проверку

(тени в хроме при выборе из меню в автозаполнении исправлю в вебките)

2021-04-07 16:45 UTC, Sarafa2n requested changes

2021-04-07 16:45 UTC, Sarafa2n commented on src/consts/consts.js
> +    backendURL: 'http://127.0.0.1:8080',
кажет я что-то побьется, давай это уберем, и вынесем в process.env

2021-04-07 16:45 UTC, Sarafa2n commented on src/utils/utils.js
> +  }
давай переделаем на forEach

2021-04-07 16:45 UTC, Sarafa2n commented on src/views/loginView/loginView.js
> +    if (Array.from(document.querySelectorAll('.errors')).find((el) => el.innerHTML !== '')) {
давай вынесем это в отдельную переменную

2021-04-07 16:45 UTC, Sarafa2n commented on src/views/loginView/loginView.scss
> +    background-color: rgba(33, 36, 40, 0.3);
цвет в палитру

2021-04-07 16:45 UTC, Sarafa2n commented on src/views/signupView/signupView.js
> +    }
если у нас такая конструкция повторяется давай ее в отдельную функцию вынесем

2021-04-07 16:45 UTC, Sarafa2n commented on src/views/signupView/signupView.js
> +    if (Array.from(document.querySelectorAll('.errors')).find((el) => el.innerHTML !== '')) {
выше отписал

2021-04-07 19:13 UTC, doomwastaken commented on src/consts/consts.js
> +    backendURL: 'http://127.0.0.1:8080',
будет исправлено в ветке с бандлером  (завтра-послезавтра)

2021-04-07 19:13 UTC, doomwastaken commented on src/utils/utils.js
> +  }
fixed

2021-04-07 19:13 UTC, doomwastaken commented on src/views/loginView/loginView.js
> +    if (Array.from(document.querySelectorAll('.errors')).find((el) => el.innerHTML !== '')) {
fixed

2021-04-07 19:13 UTC, doomwastaken commented on src/views/loginView/loginView.scss
> +    background-color: rgba(33, 36, 40, 0.3);
fixed

2021-04-07 19:14 UTC, doomwastaken commented on src/views/signupView/signupView.js
> +    }
создал родительскую вьюху, закинул все вместе

2021-04-07 19:14 UTC, doomwastaken commented on src/views/signupView/signupView.js
> +    if (Array.from(document.querySelectorAll('.errors')).find((el) => el.innerHTML !== '')) {
аналогично

2021-04-08 20:10 UTC, Sarafa2n requested changes

2021-04-08 20:10 UTC, Sarafa2n commented on src/views/authViews/authView.js
> +    }
смотри, вы же это будете использовать не только в login и signup, а к примеру в профиле, ток там обратная ситуация, так что это лучше вынести просто в функцию, а не во вьюху

2021-04-08 20:10 UTC, Sarafa2n commented on src/views/authViews/signupView/signupView.js
> +    const inputErrors = [...document.querySelectorAll('.errors')].find((el) => el.innerHTML !== '');
ты берешь ошибки, а потом делаешь это еще раз, давай это исправим

2021-04-09 20:44 UTC, doomwastaken commented on src/views/authViews/signupView/signupView.js
> +    const inputErrors = [...document.querySelectorAll('.errors')].find((el) => el.innerHTML !== '');
Исправил, больше никаких проверок через поиску по html)

2021-04-09 20:44 UTC, doomwastaken commented on src/views/authViews/authView.js
> +    }
данную конструкцию больше не будем использовать, а дублирование убрано с созданием родительского класса

2021-04-10 09:05 UTC, Sarafa2n approved these changes

2021-04-10 13:18 UTC, GrateJastes approved these changes, later dismissed

2021-04-10 13:26 UTC, merged