CM-26_FeedPage
frontend-park-mail-ru/2021_1_Code_Magicians pull request #20
Opened 2021-04-07 15:54 UTC by GrateJastes

2021-04-07 17:06 UTC, Sarafa2n requested changes

2021-04-07 17:06 UTC, Sarafa2n commented on src/consts/consts.js
> +    backendURL: 'http://127.0.0.1:8080',
эм, кажется это побьет

2021-04-07 17:06 UTC, Sarafa2n commented on src/views/profileViews/profilePinsView/profilePinsView.js
> +    this._nestedComponents.set('_pinsFeed', new PinsFeed({...this.props}));
кажется нарушена логика, надо `pins` прокидывать в `PinsFeed` или же пробежаться по `pins` и сделать много `PinsFeed`

2021-04-08 19:55 UTC, Sarafa2n requested changes

2021-04-08 19:55 UTC, Sarafa2n commented on src/appManagers/router.js
> +    if (path === '/home') {
а если `/home/`

2021-04-08 19:55 UTC, Sarafa2n commented on src/appManagers/router.js
> +    window.addEventListener('click', (ev) => {
давай писать `event`

2021-04-08 19:55 UTC, Sarafa2n commented on src/components/sidebar/sidebar.js
> +          const currLocation = window.location.pathname === '/' ? '/home' : window.location.pathname;
тут тоже самое

2021-04-08 19:55 UTC, Sarafa2n commented on src/views/notFoundView/notFoundView.js
> +    this.back = (ev) => appRouter.back();
event

2021-04-08 19:55 UTC, Sarafa2n commented on src/views/profileViews/profilePinsView/profilePinsView.js
> +}));
кажется это повторяется, давай это вынесем в consts

2021-04-08 20:32 UTC, GrateJastes commented on src/components/sidebar/sidebar.js
> +          const currLocation = window.location.pathname === '/' ? '/home' : window.location.pathname;
См. роутер

2021-04-09 20:11 UTC, Sarafa2n requested changes

2021-04-09 20:11 UTC, Sarafa2n commented on src/components/pinsFeed/pinsFeed.scss
> +    //position: relative;  // it crushes the layout :(
лучше уж вовсе убрать

2021-04-10 09:16 UTC, Sarafa2n approved these changes

2021-04-10 09:20 UTC, merged