Dev
frontend-park-mail-ru/2021_1_Code_Magicians pull request #25
Opened 2021-04-13 15:15 UTC by GrateJastes

2021-04-28 16:55 UTC, Sarafa2n requested changes

2021-04-28 16:55 UTC, Sarafa2n commented on src/appManagers/app.js
> +import 'assets/img/Logo.png';
а где используется ?

2021-04-28 16:55 UTC, Sarafa2n commented on src/appManagers/dispatcher.js
> +    const ID = `ID_${this._nextID++}`;
давай индекс увеличивать после

2021-04-28 16:55 UTC, Sarafa2n commented on src/components/page/page.js
> +import {userStore} from 'stores/userStore/UserStore';
давай перенесем на верх, последними импортами делать css hbs и jpg

2021-04-28 16:55 UTC, Sarafa2n commented on src/components/page/page.js
> +        imageLink: '/assets/img/Logo.png',
import

2021-04-28 16:55 UTC, Sarafa2n commented on src/components/profileChanges/profileChanges.js
> +import {validateInputs} from 'utils/validateUtils';
тут тоже

2021-04-28 16:55 UTC, Sarafa2n commented on src/components/profileHeader/profileHeader.js
> +import {toastBox} from 'components/toast/toast';
и тут

2021-04-28 16:55 UTC, Sarafa2n commented on src/components/securitySettings/securitySettings.js
> +import {validateInput} from 'utils/validateUtils';
0_0

2021-04-28 16:55 UTC, Sarafa2n commented on src/models/NotificationModel.js
> +    props.logoLink = props.logoLink ? `${constants.network.bucketURL}${props.logoLink}` : '/assets/img/Logo.png';
можно сделать импорт картинки

2021-04-28 16:55 UTC, Sarafa2n commented on src/sw.js
> +];
нельзя хардкодить файлы

2021-04-28 16:55 UTC, Sarafa2n commented on src/views/pinBuilderView/pinBuilderView.scss
> +  }
?

2021-04-28 16:55 UTC, Sarafa2n commented on webpack.config.js
> +      },
а где babel?

2021-04-29 08:21 UTC, GrateJastes commented on src/appManagers/dispatcher.js
> +    const ID = `ID_${this._nextID++}`;
? Так оно так и происходит, постинкремент же. После этого this._nextID больше не используется в методе, это вообще его единственное использование

2021-05-04 11:30 UTC, Sarafa2n approved these changes

2021-05-04 11:48 UTC, merged