fixes for pin view/creation && board creation
frontend-park-mail-ru/2021_1_Code_Magicians pull request #26
Opened 2021-05-04 11:51 UTC by doomwastaken

2021-05-04 11:59 UTC, Sarafa2n requested changes

2021-05-04 11:59 UTC, Sarafa2n commented on src/components/boardControl/boardControl.js
> +  createBoard(event) {
Переименуй функцию, делает не то что написано

2021-05-04 11:59 UTC, Sarafa2n commented on src/components/boardControl/boardControl.scss
> +  background-image: url("data:image/svg+xml;utf8,<svg fill='gray' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 10l5 5 5-5z'/><path d='M0 0h24v24H0z' fill=
зачем так?

2021-05-05 07:59 UTC, doomwastaken commented on src/components/boardControl/boardControl.js
> +  createBoard(event) {
fixed showBoardForm / hideBoardForm

2021-05-05 07:59 UTC, doomwastaken commented on src/components/boardControl/boardControl.scss
> +  background-image: url("data:image/svg+xml;utf8,<svg fill='gray' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 10l5 5 5-5z'/><path d='M0 0h24v24H0z' fill=
вернул стандартный

2021-05-05 08:00 UTC, Sarafa2n approved these changes

2021-05-05 08:10 UTC, merged